project_id = "xsypxtfjffgihnmcjfgc"

[functions.ai-educational-assistant]
verify_jwt = false

[functions.enhanced-feature-matcher]
verify_jwt = false

[functions.lifestyle-tech-analyzer]
verify_jwt = false

[functions.ai-technology-readiness]
verify_jwt = false

[functions.ai-technology-checklist]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
