
# Netlify configuration file

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Make sure the redirect is forced

# Specific redirect for compare models page
[[redirects]]
  from = "/models/compare"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/compare-models"
  to = "/index.html"
  status = 200
  force = true

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
