
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "upgrade-insecure-requests; default-src 'self' *.lovableproject.com *.lovable.app; connect-src 'self' wss://*.lovableproject.com ws://*.lovableproject.com *.lovableproject.com *.lovable.app; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob: https://*;"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure WebSocket connections are properly handled
[[headers]]
  for = "/@vite/client"
    [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript; charset=UTF-8"

# Additional MIME type definitions
[[headers]]
  for = "/*.svg"
    [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.png"
    [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
    [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.gif"
    [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/*.webp"
    [headers.values]
    Content-Type = "image/webp"

[[headers]]
  for = "/*.woff"
    [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/*.woff2"
    [headers.values]
    Content-Type = "font/woff2"
