
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
