
# Netlify configuration file with bot detection and prerendering

# Static files are served directly by default, no redirects needed for them

# Enhanced bot detection and prerendering - TEMPORARILY DISABLED FOR DEBUGGING
# [[edge_functions]]
#   function = "bot-detector"
#   path = "/*"

# Specific redirects for compare models pages (high priority)
[[redirects]]
  from = "/compare-models"
  to = "/index.html"
  status = 200
  force = true
  
[[redirects]]
  from = "/models/compare"
  to = "/index.html"
  status = 200
  force = true

# Blog post redirects
[[redirects]]
  from = "/blog/solar-power-solutions-for-full-time-rvers"
  to = "/blog/solar-power-solutions"
  status = 301
  force = true

# Legacy model paths
[[redirects]]
  from = "/models/luxury-class"
  to = "/models/luxury"
  status = 301
  force = true

# Legacy feature paths
[[redirects]]
  from = "/rv-intelligence/*"
  to = "/features/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/rv-systems/*"
  to = "/features/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/rv-tools/*"
  to = "/calculators/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/support/*"
  to = "/troubleshooting/:splat"
  status = 301
  force = true

# Auth error handling
[[redirects]]
  from = "/auth/error"
  to = "/auth"
  status = 301
  force = true

# Handle 404 redirects for invalid routes (detected by edge function)
[[redirects]]
  from = "/404-redirect"
  to = "/index.html"
  status = 404

# SPA fallback for valid routes - must be last to avoid intercepting static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings  
[build]
  command = "npm ci && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

# Comprehensive security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Allow necessary resources for RV tech site
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://tagmanager.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.mapbox.com https://www.google-analytics.com https://analytics.google.com *.supabase.co; frame-src 'self' https://www.google.com; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self';"
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=(), usb=(), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"

# Specific headers for static assets
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# Enhanced security for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Service worker security
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

