import { Edge, MarkerType } from 'reactflow';

export const edges: Edge[] = [
  {
    id: 'e1-2',
    source: 'start',
    target: 'power-check',
    label: 'Power Analysis',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-3',
    source: 'start',
    target: 'network',
    label: 'Network Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-4',
    source: 'start',
    target: 'software',
    label: 'Software Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-5',
    source: 'start',
    target: 'battery',
    label: 'Power System',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-6',
    source: 'start',
    target: 'wifi',
    label: 'Network Analysis',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
];