import { Edge, MarkerType } from 'reactflow';

export const edges: Edge[] = [
  // Start to main branches
  {
    id: 'start-power',
    source: 'start',
    target: 'power-check',
    label: 'Power Analysis',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'start-network',
    source: 'start',
    target: 'network',
    label: 'Network Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'start-software',
    source: 'start',
    target: 'software',
    label: 'Software Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b' },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  // Power branch connections
  {
    id: 'power-battery',
    source: 'power-check',
    target: 'battery',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'battery-battery-system',
    source: 'battery',
    target: 'battery-system',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'battery-solar-system',
    source: 'battery',
    target: 'solar-system',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'battery-charge',
    source: 'battery',
    target: 'charge',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  // Network branch connections
  {
    id: 'network-wifi',
    source: 'network',
    target: 'wifi',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'wifi-smart-devices',
    source: 'wifi',
    target: 'smart-devices',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'smart-devices-boost',
    source: 'smart-devices',
    target: 'boost',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  // Software branch connections
  {
    id: 'software-version',
    source: 'software',
    target: 'version',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'version-update',
    source: 'version',
    target: 'update',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  // Resolution path connections
  {
    id: 'battery-system-resolved',
    source: 'battery-system',
    target: 'resolved',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'solar-system-resolved',
    source: 'solar-system',
    target: 'resolved',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'charge-resolved',
    source: 'charge',
    target: 'resolved',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'boost-resolved',
    source: 'boost',
    target: 'resolved',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'update-resolved',
    source: 'update',
    target: 'resolved',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  // Final resolution path
  {
    id: 'resolved-support',
    source: 'resolved',
    target: 'support',
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
];