import { Edge, MarkerType } from 'reactflow';

export const edges: Edge[] = [
  {
    id: 'e1-2',
    source: 'entry',
    target: 'power',
    label: 'Power Analysis',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b', rx: 4, ry: 4 },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-3',
    source: 'entry',
    target: 'network',
    label: 'Network Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b', rx: 4, ry: 4 },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-4',
    source: 'entry',
    target: 'software',
    label: 'Software Subsystem',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b', rx: 4, ry: 4 },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-5',
    source: 'entry',
    target: 'maintenance',
    label: 'Maintenance',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b', rx: 4, ry: 4 },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
  {
    id: 'e1-6',
    source: 'entry',
    target: 'support',
    label: 'Support',
    labelBgPadding: [8, 4],
    labelBgStyle: { fill: '#1e293b', rx: 4, ry: 4 },
    labelStyle: { fill: '#fff', fontSize: 12 },
    type: 'smoothstep',
    markerEnd: { type: MarkerType.ArrowClosed },
    animated: true,
    style: { stroke: '#6366f1' },
  },
];
